### ISSUE TITLE
Cannot log in with an account not in your Bitwarden vault

### ISSUE THREAD

**Issue by Hannah-GBS** [raiyni/bitwarden-plugin#1]
Clicking Login (or hitting enter) clears the password field if the typed username is not in your Bitwarden vault
![GAFeA3bZi6](https://user-images.githubusercontent.com/7504779/83897741-e2f13380-a74d-11ea-9cf3-7d76b3be5f67.gif)

**Comment by raiyni** [comment]
Added in 856ca5b9e5b678c9b4953117522b5e132775a1b2
