### ISSUE TITLE
Password field not populating

### ISSUE THREAD

**Issue by fattredd** [raiyni/bitwarden-plugin#10]
I've installed `bw` and added it to my path, as well as set the BW_SESSION envvar.  
`bw list items --search runescape.com` returns the expected json. I've run it through `jq` here to extract the usernames:
![image](https://user-images.githubusercontent.com/1054129/185680727-b00b0207-be27-48a6-976d-c8cfe21360a0.png)

Using SysInternals ProcMon I can even verify that RuneLite is indeed successfully querying `bw`. I double checked that it even has the correct session key:
![image](https://user-images.githubusercontent.com/1054129/185681914-8d3ff4ce-79a0-4adc-a1fa-3c7af2d989df.png)
  
But alas, the password field in RuneLite isn't populating. I don't know Java well enough to do any internal debugging to see what's wrong, but I've also verified that the login I'm trying to use does indeed match between bw and runelite.

Are there any other debugging steps I can take?

This issue is occurring with:
- bw-cli v1.20.0 (I saw in other issues that higher versions may cause problems. This issue still occurs with v1.22.1) 
- RuneLite 1.8.30

**Comment by raiyni** [comment]
I'm afraid I missed this issue over the years, sorry. If you still  have this problem, or another users, please let me know.
