### ISSUE TITLE
Issue After Varlamore Update

### ISSUE THREAD

**Issue by APKiwi** [raiyni/bitwarden-plugin#14]
Hi, fresh install of both macOS (Sonoma 14.4.1 (23E224)) and Runelite (latest, .dmg) I get:
<img width="413" alt="image" src="https://github.com/raiyni/bitwarden-plugin/assets/13660274/99e65e3c-04f0-4074-b40b-a5cf380449e7">
Error loading vault.

I have a manually specified bw location within RuneLite plugin settings as `/opt/homebrew/bin/bw`, my understanding this should override $PATH, but `/opt/homebrew/bin` is in the $PATH anyway.
<img width="236" alt="image" src="https://github.com/raiyni/bitwarden-plugin/assets/13660274/eace5a09-c3b5-4a4b-a911-6853544cbace">

What could potentially be breaking it (at least from a UI perspective) is that when you paste into the Bitwarden session key input, a funny character appears (instead of the '•' characters).
<img width="1284" alt="image" src="https://github.com/raiyni/bitwarden-plugin/assets/13660274/629ab1c3-99c0-4cf1-add0-fad1a90f1f65">

The terminal shows success with the following command, albeit with a deprecation warning:
<img width="640" alt="image" src="https://github.com/raiyni/bitwarden-plugin/assets/13660274/e839b77a-4a60-41f8-bffe-572eacabb260">

**Comment by DaLukasDev** [comment]
@APKiwi  I do have the same issue with the brew installed version of bitwarden CLI.
However downloading the latest release from the Bitwarden CLI and using that binary instead works just fine.

**Comment by raiyni** [comment]
This might be due to the deprecation warning from the Node version that the brew uses.

**Comment by APKiwi** [comment]
I uninstalled bitwarden-cli from homebrew, and I installed it with npm instead (I'm on arm64 so this is the only option according to https://bitwarden.com/help/cli/#tab-npm-bI3gMs3A3z4pl0fwvRie9)

Sadly, the same exact issue

**Comment by DaLukasDev** [comment]
Could you try the native executable? Whats odd in my case is when adding that one to the $PATH it refuses to work  with just `bw` in the plugin settings (I can access it in a terminal just fine using `bw`). However an absolute path to the binary works just fine.

**Comment by APKiwi** [comment]
The native executable works when referenced in $PATH, cheers. Not ideal from a maintenance POV (not updated through NPM or homebrew) but a solution none the less, thank you.

**Comment by raiyni** [comment]
I believe this might be fixed in the latest version if it's printing to stderr.
