### ISSUE TITLE
[Feature request] Add TOTP support to automatically enter 2FA code

### ISSUE THREAD

**Issue by ErikHumphrey** [raiyni/bitwarden-plugin#2]
If you have Bitwarden Premium ($10/year), you can use Bitwarden as a TOTP authenticator / generator. It would be nice if this plugin used `bw get totp runescape` to automatically enter the user's two-factor authentication code, if the user has Bitwarden Premium and have set it up. 

### Reason for implementation

*Old School RuneScape* will ask you for the 6-digit code generated by your authenticator app, slowing down logins. You can ask it to remember this every 30 days, but not indefinitely. You can get around this on the main *RuneScape* by signing in with a linked Google Account or Apple ID, but *Old School RuneScape* doesn't allow logging in with these options.

### Implementation

* It's not too different from how the plugin already fetches the credentials for `runescape.com`, but the TOTP is a different entry, I think, so it might have to search for something else like `runescape`, as mentioned above.
* It should probably be a checkbox option in the plugin settings, as most users will not have Bitwarden Premium and some may not want their 2FA code automatically entered.

### Help

* I'm willing to try subscribing to Bitwarden Premium to help test (and possibly help implement) this feature.

**Comment by ErikHumphrey** [comment]
I've Bitwarden Premium now, so I'm going to try and implement this some time soon.

**Comment by AliceDTRH** [comment]
Any progress on this? If not I'd be willing to look at it.

**Comment by ErikHumphrey** [comment]
> Any progress on this?

Nope!

**Comment by ErikHumphrey** [comment]
I'm no longer planning on looking at this because Jagex Accounts remove any need for the Bitwarden plugin. While still possible, closing as not done; please feel free to reopen.
