### ISSUE TITLE
Cannot access vault w/ Mac OS

### ISSUE THREAD

**Issue by MikeSim1** [raiyni/bitwarden-plugin#3]
While this plugin works on my Windows computer, my Mac running the latest beta of Big Sur does not work. Unsure if it's the plugin or bitwarden-cli not playing nice with the new OS, but I've tried manually copy and pasting the session keys after multiple fresh logins, unlocks, etc. and none will allow access to the vault. I've also exported various session keys to .bash_profile as well as created a new .profile just to see if that would work, but it did not. I've yet to set this up on a Mac, so I may be going wrong somewhere else, but I can't think of anything obvious that I'm doing wrong.

**Comment by MikeSim1** [comment]
I should also note that I can access items with the same session keys I'm attempting to use with the plugin, even in fresh terminal sessions. I also have all permissions enabled in security, so it shouldn't be a permissions issue or anything.

**Comment by raiyni** [comment]
I don't have access to OSX but make sure BW is accessible in your path.

**Comment by MikeSim1** [comment]
BW is definitely accessible in my path, I also tried adding permissions to the directory but it didn't fix the issue...

**Comment by MikeSim1** [comment]
I may have found the issue... It's failing to decrypt my vault for some reason

**Comment by raiyni** [comment]
Are you getting that error when you are using BW cli by hand?

**Comment by MikeSim1** [comment]
Yes

**Comment by MikeSim1** [comment]
I had some time to revisit this and figure it out finally... It's a Mac OS issue in general. The way that the BW_SESSION variable needs to be set _**(before running RuneLite, otherwise you will need to restart the application for this change to apply)**_ is by using:`launchctl setenv BW_SESSION "YOUR_SESSION_KEY_HERE"`
This sets the variable system wide. Setting it in ~/.bash_profile does not work as that is the profile for the terminal session. I tested this by simply running the command with varying strings, and running my own Java program that literally just prints the variable the same way that the plugin does. However, the plugin still fails to connect to BWCLI somehow. With my one line program (literally just `System.out.println(System.getenv("BW_SESSION"));`) I get the correct String back after setting it and restarting the IDE. Running RuneLite, or even manually entering the String does not work.

**Comment by MikeSim1** [comment]
Is there a reason this was closed when it wasn't solved?

**Comment by raiyni** [comment]
I miss read your last comment as fixed. If you are using the Runelite dmg,  you can try using the .jar.  Or I can possibly build debugging information into the plugin.

**Comment by raiyni** [comment]
Closing this as stale. This might be fixed by the latest version, if not would need help investigating.
