### ISSUE TITLE
Error Loading Vault

### ISSUE THREAD

**Issue by ibrokemypie** [raiyni/bitwarden-plugin#4]
My bitwarden vault is logged in and works just fine with the bitwarden cli, for example 'bw get password runescape.com' does return my password 2without any further input required. However my vault is self hosted and I think this may be the reason it doesnt work with his runelite plugin, even if I do bw unlock and copy a new session key it still just reports error loading vault.
![image](https://user-images.githubusercontent.com/7827846/95669807-3bd74980-0bd0-11eb-8f57-c6f561289f07.png)

**Comment by raiyni** [comment]
I don't think this works with the bitwarden rust server. Make sure bw is in your PATH I guess.

**Comment by iligalodin** [comment]
currently facing a similar issue! i can also get into bw via CLI set my session key and getting the same error, i am fairly sure bw is in my path

**Comment by BSeboo** [comment]
Similar story here: it seems the plugin doesn't work with "linux". Had it working on multiple windows 10 machines, also tested in on a couple of distros without success: Fedora 33 & 34; Ubuntu 20.10, PopOS 20.10 & 20.04 via  some methods: snaps, AppImage, deb/rpm packages.

**Comment by raiyni** [comment]
> Similar story here: it seems the plugin doesn't work with "linux". Had it working on multiple windows 10 machines, also tested in on a couple of distros without success: Fedora 33 & 34; Ubuntu 20.10, PopOS 20.10 & 20.04 via some methods: snaps, AppImage, deb/rpm packages.

If you are able to dump the output from the plugin while running in a dev environment, that would be great. I can't setup a VM environment for linxu right now for whatever reason. I can try using a VM in unraid later.

**Comment by raiyni** [comment]
> Similar story here: it seems the plugin doesn't work with "linux". Had it working on multiple windows 10 machines, also tested in on a couple of distros without success: Fedora 33 & 34; Ubuntu 20.10, PopOS 20.10 & 20.04 via some methods: snaps, AppImage, deb/rpm packages.

I would try with the all platform jar from runelite.net. I think this stems from not being able to access the path in AppImage?

**Comment by CageCodes** [comment]
I can confirm that using the all platform jar allows the plugin to work. 
Tested on Ubuntu 20.04.2 LTS

**Comment by BSeboo** [comment]
Indeed it looks like with the all-platforms jar for RuneLite it works correctly.(I was using the AppImage / Lutris(which still uses the AppImage version presumably) ) 
The issue for me personally is solved.
If there's not too much trouble however it would be nice to be able to select the folder/path in case auto-detection fails(maybe through the plugin settings, if possible).
I understand though that this is beyond the scope so far.Cheers and thanks for the plugin.

**Comment by raiyni** [comment]
> Indeed it looks like with the all-platforms jar for RuneLite it works correctly.(I was using the AppImage / Lutris(which still uses the AppImage version presumably) )
> The issue for me personally is solved.
> If there's not too much trouble however it would be nice to be able to select the folder/path in case auto-detection fails(maybe through the plugin settings, if possible).
> I understand though that this is beyond the scope so far.Cheers and thanks for the plugin.

I've thought about creating a config to specify path to the executable but I haven't been able to create linux VM's for a while now to test if it even fixes the appimage.

**Comment by raiyni** [comment]
Added a configurable path in the recent version.
