### ISSUE TITLE
Doesn't work with bitwarden-cli 1.21.1

### ISSUE THREAD

**Issue by JussiHuot** [raiyni/bitwarden-plugin#6]
Would be nice if it was updated to work with newest version of bitwarden-cli

**Comment by raiyni** [comment]
I have updated to 1.21.1, logged out, logged back in, and reset my session variable and it appears to work.

Are you sure bw is in your path? Or are you on mac/linux?

**Comment by JussiHuot** [comment]
I'm on linux, tried both adding it to export and pasting the key to client and both didn't work, downgraded back to 1.20.0 and it worked again.

**Comment by christianlegge** [comment]
I was seeing similar issues with 1.22.0. No error messages, just wasn't filling the password. Downgrading to 1.20.0 solved for me as well.

e: I'm on Windows 10 64-bit.

**Comment by raiyni** [comment]
> I was seeing similar issues with 1.22.0. No error messages, just wasn't filling the password. Downgrading to 1.20.0 solved for me as well.

What OS are you on? Linux?

**Comment by christianlegge** [comment]
@raiyni Windows. I edited my comment

**Comment by zertyn** [comment]
Seems not to be working for on all mentioned versions of BW CLI.

**Comment by christianlegge** [comment]
Works for me on macOS on v2022.8.0.

**Comment by raiyni** [comment]
I believe this is fixed in the latest version. Stdout and Stderror were being merged and sometimes errors get printed even though a session is valid.
